### ISSUE TITLE
How do we increase collaboration for new devs?

### ISSUE THREAD

**Issue by dguruwu** [dougbutner/beta-pseudo#1]
It seems to me you have put an extraordinary effort into learning and adopting the EOSIO codebase and have interesting, and well-formed ideas yet also lack some skillsets which you identify and improve upon continually.  Not to toot your horn, but I want to know how we can increase awareness, collaboration and participation across all ecosystems so that those who fit compatibly can merge their focus with others.  

With the upcoming release of TrustEVM I see the potential for this chasm to widen and would like to do something proactive about it.  Thoughts?

**Comment by dougbutner** [comment]
Thanks for asking Doug Wu.

Best thing to do is see something, say something via a issue. 

✅ A simple issue of what I''m doing incorrectly with an explanation or even a stack exchange article link explaining the solution can be a real time saver for me. 

I could also help by doing an issues template. It's a weird point about describing how to jump in, so I do recommend any interested cpp devs contact me if they want to get involved in a more meaningful way. 

Trust isn't relevant to this repo, as we are on a different technology, and the contract languages aren't compatible. Plus we aren't an EOS dapp, we're a WAX dapp.

**Comment by dougbutner** [comment]
Also please keep issues on-topic. Your question can be read to have nothing to do witht the smart contracts. This isn't the place to talk about EOS or philosophy. This is space for issues on the design C++ contracts for cXc.world, a WAX dapp

**Comment by dguruwu** [comment]
Thanks for explaining that.  Sorry I was off-topic.  I have a tendency to do that because I don't know where to ask my questions or get answers so I end up trying novel approaches to see what happens.  Forgive me.  :-)
